### ISSUE TITLE
SUDENELY SOME ERROR Pl do help

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#1]
Traceback (most recent call last):
  File "C:\Users\CSROF\Downloads\PyroEdgeGPTBot-master\PyroEdgeGPTBot-master\PyroEdgeGptBot.py", line 100, in <module>
    "bot": Chatbot(cookie_path=COOKIE_FILE), # 共用一个 cookie.json 文件
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CSROF\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 596, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File "C:\Users\CSROF\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py", line 408, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'

**Comment by CSR-SOFTWARES** [comment]
tried everything new cookie even

**Comment by tom-snow** [comment]
Please give me more information.

Python Version:
System Version:
EdgeGPT Version:

**Comment by CSR-SOFTWARES** [comment]
I Tried to update the version of edgeGpt intiallly it worked then same error

**Comment by tom-snow** [comment]
I tested on Linux (ubuntu 22.10) and seems everything works well. 
Python: 3.11.2 (new env created by conda)
Pip: 23.0.1

<details>
  <summary>
output of command `pip freeze`
  </summary>
<code>
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
async-timeout==4.0.2
attrs==23.1.0
BingImageCreator==0.1.5
certifi==2023.5.7
charset-normalizer==3.1.0
EdgeGPT==0.3.8
frozenlist==1.3.3
h11==0.14.0
httpcore==0.17.0
httpx==0.24.0
idna==3.4
markdown-it-py==2.2.0
mdurl==0.1.2
multidict==6.0.4
prompt-toolkit==3.0.38
pyaes==1.6.1
Pygments==2.15.1
Pyrogram==2.0.106
PySocks==1.7.1
python-dotenv==1.0.0
pytz==2023.3
regex==2023.5.5
requests==2.30.0
rich==13.3.5
sniffio==1.3.0
TgCrypto==1.2.5
urllib3==2.0.2
wcwidth==0.2.6
websockets==11.0.3
yarl==1.9.2
</code>
</details>


I'll try run it on windows to reproduce it later

**Comment by tom-snow** [comment]
Seems this is upstream's(EdgeGPT) bug, and this bug appears randomly.
My log:
```
❯ conda activate PyroEdge11
❯ python PyroEdgeGptBot.py
2023-05-10 21:43:44 - httpx - INFO - HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/root/gptBot/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 100, in <module>
    "bot": Chatbot(cookie_path=COOKIE_FILE), # 共用一个 cookie.json 文件
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/share/miniconda3/envs/PyroEdge11/lib/python3.11/site-packages/EdgeGPT.py", line 603, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File "/opt/share/miniconda3/envs/PyroEdge11/lib/python3.11/site-packages/EdgeGPT.py", line 415, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'
❯ python PyroEdgeGptBot.py
2023-05-10 21:50:36 - httpx - INFO - HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/root/gptBot/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 100, in <module>
    "bot": Chatbot(cookie_path=COOKIE_FILE), # 共用一个 cookie.json 文件
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/share/miniconda3/envs/PyroEdge11/lib/python3.11/site-packages/EdgeGPT.py", line 603, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File "/opt/share/miniconda3/envs/PyroEdge11/lib/python3.11/site-packages/EdgeGPT.py", line 415, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'
❯ python PyroEdgeGptBot.py
2023-05-10 21:50:39 - httpx - INFO - HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/root/gptBot/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 100, in <module>
    "bot": Chatbot(cookie_path=COOKIE_FILE), # 共用一个 cookie.json 文件
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/share/miniconda3/envs/PyroEdge11/lib/python3.11/site-packages/EdgeGPT.py", line 603, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File "/opt/share/miniconda3/envs/PyroEdge11/lib/python3.11/site-packages/EdgeGPT.py", line 415, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'
❯ python PyroEdgeGptBot.py
2023-05-10 21:50:42 - httpx - INFO - HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
2023-05-10 21:50:43 - httpx - INFO - HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
2023-05-10 21:50:43 - pyrogram.connection.connection - INFO - Connecting...
2023-05-10 21:50:43 - pyrogram.connection.connection - INFO - Connected! Production DC4 - IPv4
2023-05-10 21:50:43 - pyrogram.session.session - INFO - NetworkTask started
2023-05-10 21:50:44 - pyrogram.session.session - INFO - Session initialized: Layer 158
2023-05-10 21:50:44 - pyrogram.session.session - INFO - Device: CPython 3.11.2 - Pyrogram 2.0.106
2023-05-10 21:50:44 - pyrogram.session.session - INFO - System: Linux 5.19.0-41-generic (en)
2023-05-10 21:50:44 - pyrogram.session.session - INFO - Session started
2023-05-10 21:50:44 - pyrogram.session.session - INFO - PingTask started
2023-05-10 21:50:45 - pyrogram.dispatcher - INFO - Started 8 HandlerTasks
^C2023-05-10 21:50:45 - root - INFO - Stop signal received (SIGINT). Exiting...
2023-05-10 21:50:49 - pyrogram.dispatcher - INFO - Stopped 8 HandlerTasks
2023-05-10 21:50:49 - pyrogram.session.session - INFO - PingTask stopped
2023-05-10 21:50:49 - pyrogram.connection.connection - INFO - Disconnected
2023-05-10 21:50:49 - pyrogram.session.session - INFO - NetworkTask stopped
2023-05-10 21:50:49 - pyrogram.session.session - INFO - Session stopped

root@pyro #

```

**Comment by tom-snow** [comment]
try pull the newest [PyroEdgeGPTBot](https://github.com/tom-snow/PyroEdgeGPTBot) and run the bot.

**Comment by tom-snow** [comment]
Did you tested?
