### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Eikosa** [tom-snow/PyroEdgeGPTBot#13]
```
2023-05-22 16:33:47 - root - ERROR - [chat_handle, unexpected error]: 502, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
2023-05-22 16:33:47 - pyrogram.dispatcher - ERROR - 502, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 345, in chat_handle
    raise e
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 332, in chat_handle
    async for final, response, reply_markup in bingAIStream(update.chat.id, update.text):
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 547, in bingAIStream
    async for final, rsp in  EDGES[user_id]["bot"].ask_stream(prompt=messageText, conversation_style=EDGES[user_id]["style"]):
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 673, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 453, in ask_stream
    self.wss = await self.session.ws_connect(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 792, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 502, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
```

**Comment by tom-snow** [comment]
Seems this is an error of upstream ( bing / EdgeGPT closed connection unexpectedly ).

You should just try again
