### ISSUE TITLE
Ask two prompts in a row

### ISSUE THREAD

**Issue by Eikosa** [tom-snow/PyroEdgeGPTBot#14]
It gives this error when prompted twice in a row:

```sh
root@kelime:~/PyroEdgeGPTBot# sudo python3 PyroEdgeGptBot.py 
/root/PyroEdgeGPTBot/PyroEdgeGptBot.py:106: DeprecationWarning: There is no current event loop
  tmpLoop = asyncio.get_event_loop()
2023-05-22 17:52:36 - root - ERROR - [chat_handle, unexpected error]: 'NoneType' object has no attribute 'split'
2023-05-22 17:52:36 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7faa98a08340>
2023-05-22 17:52:36 - pyrogram.dispatcher - ERROR - 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 345, in chat_handle
    raise e
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 332, in chat_handle
    async for final, response, reply_markup in bingAIStream(update.chat.id, update.text):
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 547, in bingAIStream
    async for final, rsp in  EDGES[user_id]["bot"].ask_stream(prompt=messageText, conversation_style=EDGES[user_id]["style"]):
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 673, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 510, in ask_stream
    objects = msg.data.split(DELIMITER)
AttributeError: 'NoneType' object has no attribute 'split'
2023-05-22 17:52:36 - root - ERROR - [chat_handle, unexpected error]: 'messages'
2023-05-22 17:52:36 - pyrogram.dispatcher - ERROR - 'messages'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 345, in chat_handle
    raise e
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 332, in chat_handle
    async for final, response, reply_markup in bingAIStream(update.chat.id, update.text):
  File "/root/PyroEdgeGPTBot/PyroEdgeGptBot.py", line 547, in bingAIStream
    async for final, rsp in  EDGES[user_id]["bot"].ask_stream(prompt=messageText, conversation_style=EDGES[user_id]["style"]):
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 673, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 575, in ask_stream
    response["item"]["messages"][-1]["contentOrigin"] == "Apology"
KeyError: 'messages'
^C^C^Z
[1]+  Stopped                 sudo python3 PyroEdgeGptBot.py
root@kelime:~/PyroEdgeGPTBot# 
```

**Comment by tom-snow** [comment]
https://github.com/tom-snow/PyroEdgeGPTBot/issues/4#issuecomment-1547273493

**Comment by CSR-SOFTWARES** [comment]
I would suggest try new bing account with new cookie file and before using new cookie must login and chat with bing for atleast 10 messages .
this may  remove your error

**Comment by tom-snow** [comment]
Send two message to a conversation the same time is impossible, you must wait the first message be answered then send the second.
