### ISSUE TITLE
ImageGenerationError

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#17]
2023-05-30 13:18:26 - root - WARNING - Allow everyone mode
2023-05-30 13:18:26 - root - WARNING - You set BING_COOKIE to None, but you allowed everyone to use this bot
2023-05-30 13:18:54 - root - ERROR - ImageGenerator Error: Redirect failed
Traceback (most recent call last):
  File "F:\AI\PyroEdgeGPTBot-master\PyroEdgeGPTBot-master\PyroEdgeGptBot.py", line 597, in set_suggest_mode_handle
    images = await image_gen_main(prompt,image_gen_cookie_u)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\PyroEdgeGPTBot-master\PyroEdgeGPTBot-master\PyroEdgeGptBot.py", line 1310, in image_gen_main
    images = await image_generator.get_images(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CSROF\AppData\Local\Programs\Python\Python311\Lib\site-packages\BingImageCreator.py", line 257, in get_images
    raise Exception("Redirect failed")
Exception: Redirect failed
2023-05-30 13:21:20 - root - WARNING - User [6249895422] try to set cookie but been rejected (not initialized).
2023-05-30 13:22:14 - root - ERROR - ImageGenerator Error: Redirect failed
Traceback (most recent call last):
  File "F:\AI\PyroEdgeGPTBot-master\PyroEdgeGPTBot-master\PyroEdgeGptBot.py", line 597, in set_suggest_mode_handle
    images = await image_gen_main(prompt,image_gen_cookie_u)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\PyroEdgeGPTBot-master\PyroEdgeGPTBot-master\PyroEdgeGptBot.py", line 1310, in image_gen_main
    images = await image_generator.get_images(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CSROF\AppData\Local\Programs\Python\Python311\Lib\site-packages\BingImageCreator.py", line 257, in get_images
    raise Exception("Redirect failed")
Exception: Redirect failed

**Comment by CSR-SOFTWARES** [comment]
EveryImage request have the same issue 
updated the cookie twice with even the new accounts too 
( althrough its up stream errror but if You can help ??)

**Comment by tom-snow** [comment]
https://github.com/tom-snow/PyroEdgeGPTBot/blob/877bb3d5fc577c8b9d617a06acbcbd5667e1e6bc/PyroEdgeGptBot.py#L113

Here should be “ You set BING_COOKIE to not None, but you allowed everyone to use this bot”.


And… Did you use “/update “ command first?

**Comment by CSR-SOFTWARES** [comment]
Yeah it's set to None 
Only ans I don't used /update yet

**Comment by CSR-SOFTWARES** [comment]
Should I use /update then try again ?

**Comment by tom-snow** [comment]
Sure

**Comment by CSR-SOFTWARES** [comment]
STC'S AI: Updated!

EdgeGPT: 0.6.2 -> 0.6.10
BingImageCreator: 0.2.1 -> 0.3.0



After this too same error in image generation

**Comment by tom-snow** [comment]
Should report to upstream repo.

I have the same error

**Comment by CSR-SOFTWARES** [comment]
I don't think they can help us because I in past I reported the same issue to them 
Not worked .
But for a chance You can

**Comment by tom-snow** [comment]
may fixed

**Comment by CSR-SOFTWARES** [comment]
Ig let's report  to them .

**Comment by tom-snow** [comment]
tried new version?

**Comment by CSR-SOFTWARES** [comment]
Yeah I did

**Comment by CSR-SOFTWARES** [comment]
Not working

**Comment by tom-snow** [comment]
my bot can work now, update cookie first

**Comment by CSR-SOFTWARES** [comment]
Alright let me do

**Comment by tom-snow** [comment]
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/79245287/0f43927d-4909-42c0-a094-98e327275d01)

**Comment by CSR-SOFTWARES** [comment]
I tried new version 
its not respodning to command

**Comment by CSR-SOFTWARES** [comment]
should I set cookie using /cookie command ?
then it will work ?

**Comment by tom-snow** [comment]
set cookie after restart if you not provide cookie by default

**Comment by CSR-SOFTWARES** [comment]
I provided default cookie

**Comment by tom-snow** [comment]
try update cookie

**Comment by CSR-SOFTWARES** [comment]
I tried every way You said and updated cookie twice 
 
 still 
 
 ImageGenerator Error: Redirect failed.

ImageGenerator Usage: /image_gen <prompt>

!!!

**Comment by CSR-SOFTWARES** [comment]
Text is working well but images are showing redirect failed error

**Comment by tom-snow** [comment]
@PyroEdgeGptBot

test, if still error, your cookie issue

**Comment by CSR-SOFTWARES** [comment]
same error with bot too

**Comment by CSR-SOFTWARES** [comment]
I Tried same way to copy cookie from bing.com

Browser chrome

**Comment by tom-snow** [comment]
https://github.com/tom-snow/PyroEdgeGPTBot/issues/3#issuecomment-1546509724

**Comment by CSR-SOFTWARES** [comment]
I tried this too 
still...

**Comment by CSR-SOFTWARES** [comment]
if You don't mind can you share me one of Your cookie file 
just to test ?

@I_AM_CSR (here tele)

**Comment by tom-snow** [comment]
I will not send you cookies, you need to switch your accounts yourself to find available cookies

**Comment by CSR-SOFTWARES** [comment]
I myself switched accounts two time 
even created a new account still

**Comment by CSR-SOFTWARES** [comment]
alright 
let it be , I will try new cookie from some other IP 
Totally new version 

Thanks for Your help 

Here's the  bot which working because of Your work(repo)
 @AI_INDIA_BOT 
I hope You will check it once ( as I updated some code ) ....  :)

**Comment by tom-snow** [comment]
No one can get the source code from only a telegram bot.

And you tested on the original @PyroEdgeGptBot and still can't work, this means your cookie issue, I can't help, you only can change your cookie ( from edge and clean home broadband ip may help )

**Comment by CSR-SOFTWARES** [comment]
Ysh You are right source code option removed because was not need 
and abt cookie I am trying .
