### ISSUE TITLE
Replit issue when I try to Run it

### ISSUE THREAD

**Issue by nonoradke** [tom-snow/PyroEdgeGPTBot#24]
2024-02-03 17:45:38 - root - INFO - BING_COOKIE loaded from ./cookie.json
2024-02-03 17:45:38 - root - WARNING - Allow everyone mode
2024-02-03 17:45:38 - root - WARNING - You set BING_COOKIE to not None, but you allowed everyone to use this bot
2024-02-03 17:45:39 - httpx - INFO - HTTP Request: GET https://www.bing.com/turing/conversation/create "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/home/runner/PyroEdgeGPTBot/main.py", line 130, in <module>
    "bot": tmpLoop.run_until_complete(EdgeGPT.Chatbot.create(proxy=PROXY_BING, cookies=BING_COOKIE)), # 共用一个 cookie.json 文件
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/PyroEdgeGPTBot/.pythonlibs/lib/python3.10/site-packages/EdgeGPT/EdgeGPT.py", line 41, in create
    self.chat_hub = ChatHub(
  File "/home/runner/PyroEdgeGPTBot/.pythonlibs/lib/python3.10/site-packages/EdgeGPT/chathub.py", line 42, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'

how to fix this issue?

**Comment by vpsbykaif** [comment]
You can fix this issue by changing the requirements.txt just remove the edgegpt and this url. `git+https://github.com/vpsbykaif/EdgeGPT@main#egg=EdgeGPT`. After adding type in the terminal `pip install -r requirements.txt --upgrade` hope it will work:




Before : 
![Screenshot_20240211_122428_Chrome](https://github.com/tom-snow/PyroEdgeGPTBot/assets/149788775/1dae49cc-b959-4c18-b1a3-f0c91663675a)


After adding the url in the requirements.txt file:
![Screenshot_20240211_122614_Chrome](https://github.com/tom-snow/PyroEdgeGPTBot/assets/149788775/61e94e1b-b5cb-455d-9160-0da32a09948a)
